// DO NOT EDIT — generated by scripts/generate-schema-types.mjs
// Source: submodules/datam8-generator/datam8-model/schema/
// Regenerate: npm run generate:schema-types

// ---- common.json ----

export type Id = number;

/**
 * An attribute of a model entity.
 */

export interface Common {
  [k: string]: unknown;
}

// ---- property.json ----

export interface Property {
  name: string;
  displayName: string;
  schema?: string;
  scopes?: PropertyScope[];
  [k: string]: unknown;
}
/**
 * Defines for which type of entities a `PropertyType` is available for assignment.
 *
 * This interface was referenced by `Property`'s JSON-Schema
 * via the `definition` "PropertyScope".
 */

export interface PropertyScope {
  type: string;
  /**
   * Defines if the `PropertyType` can only be assigned once to entities in this scope.
   */
  singleUsage?: boolean;
  mandatory?: boolean;
}
/**
 * Used to reference from any entity to a `Property`.
 *
 * This interface was referenced by `Property`'s JSON-Schema
 * via the `definition` "PropertyReference".
 */

export interface PropertyReference {
  property: string;
  value: string;
}
/**
 * A single globally available static property value that can be referenced from other entities.
 *
 * This interface was referenced by `Property`'s JSON-Schema
 * via the `definition` "PropertyValue".
 */

export interface PropertyValue {
  name: string;
  displayName?: string;
  default?: boolean;
  /**
   * The name of the associated property.
   */
  property: string;
  properties?: PropertyReference[];
  [k: string]: unknown;
}

// ---- data-type.json ----

export interface DataType {
  type: string;
  nullable: boolean;
  charLen?: number;
  precision?: number;
  scale?: number;
}
/**
 * Defines a class of data type to configure which `DataType` properties are relevant for a specific type.
 *
 * This interface was referenced by `DataType`'s JSON-Schema
 * via the `definition` "DataTypeDefinition".
 */

export interface DataTypeDefinition {
  name: string;
  displayName?: string;
  description?: string;
  hasCharLen?: boolean;
  hasPrecision?: boolean;
  hasScale?: boolean;
  /**
   * Maps target (e.g. databricks, powerbi, sqlserver) to their data types.
   */
  targets: {
    [k: string]: string;
  };
}

// ---- data-source.json ----

export type ConnectionPropertyValueType = "string" | "number" | "boolean" | "secret";

export interface DataSource {
  name: string;
  displayName?: string;
  description?: string;
  properties?: PropertyReference[];
  type: string;
  /**
   * Optional data type mappings. If not specified, uses defaults from DataSourceTypes. Individual mappings override defaults.
   */
  dataTypeMapping?: SourceDataTypeMapping[];
  /**
   * Additional properties specific to the data source
   */
  extendedProperties: {
    [k: string]: string | boolean | number;
  };
}
/**
 * Used to reference from any entity to a `Property`.
 */

export interface SourceDataTypeMapping {
  /**
   * Source system data type
   */
  sourceType: string;
  /**
   * Target system data type
   */
  targetType: string;
}
/**
 * A property or setting defined by a data source type, which is then available when defining concrete data sources.
 *
 * This interface was referenced by `DataSource`'s JSON-Schema
 * via the `definition` "ConnectionProperty".
 */

export interface ConnectionProperty {
  name: string;
  displayName?: string;
  required: boolean;
  description?: string;
  type: ConnectionPropertyValueType;
  default?: string | boolean | number;
  [k: string]: unknown;
}
/**
 * A single authentiocation method
 *
 * This interface was referenced by `DataSource`'s JSON-Schema
 * via the `definition` "AuthMode".
 */

export interface AuthMode {
  name: string;
  displayName?: string;
  /**
   * @minItems 1
   */
  required: [string, ...string[]];
  optional?: string[];
}
/**
 * Defines groups of data sources that base on their technology, e.g. `SqlServer` or `Oracle`
 *
 * This interface was referenced by `DataSource`'s JSON-Schema
 * via the `definition` "DataSourceType".
 */

export interface DataSourceType {
  /**
   * Name of the data source type (e.g., SqlDataSource, LakeSource)
   */
  name: string;
  /**
   * Human-readable display name
   */
  displayName?: string;
  /**
   * Description of the data source type
   */
  description?: string;
  /**
   * Default data type mappings for this source type
   *
   * @minItems 1
   */
  dataTypeMapping: [SourceDataTypeMapping, ...SourceDataTypeMapping[]];
  /**
   * ID of the plugin used to connect to the source type. If not provided falls back to builtin plugins matching the  name
   */
  pluginId?: string;
  /**
   * Required connection properties for this source type
   *
   * @minItems 1
   */
  connectionProperties: [ConnectionProperty, ...ConnectionProperty[]];
  /**
   * Describes different authentication modes and which connection properties are relevant for it.
   */
  authModes: AuthMode[];
}
/**
 * This interface was referenced by `DataSource`'s JSON-Schema
 * via the `definition` "SourceObject".
 */

export interface SourceObject {
  schema?: string;
  name: string;
  type: string;
  description?: string;
  properties?: PropertyReference[];
  sourceOverride?: SourceOverride;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `DataSource`'s JSON-Schema
 * via the `definition` "SourceOverride".
 */

export interface SourceOverride {
  dataSource?: string;
  sourceLocation?: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `DataSource`'s JSON-Schema
 * via the `definition` "SourceField".
 */

export interface SourceField {
  name: string;
  ordinal: number;
  dataType: string;
  maxLength?: number;
  numericPrecision?: number;
  numbericScale?: number;
  isNullable: boolean;
  isPrimaryKey?: boolean;
  description?: string;
  properties?: PropertyReference[];
  [k: string]: unknown;
}

// ---- attribute.json ----

export type HistoryType = "SCD0" | "SCD1" | "SCD2" | "SCD3" | "SCD4";

/**
 * An attribute of a model entity.
 */

export interface Attribute {
  ordinalNumber: number;
  name: string;
  displayName?: string;
  description?: string;
  attributeType: string;
  dataType: DataType;
  isBusinessKey?: boolean;
  history?: HistoryType;
  expression?: string;
  expressionLanguage?: (("sql" | "dax" | "python") | string) & string;
  unit?: string;
  refactorNames?: string[];
  dateModified?: string;
  dateDeleted?: string;
  dateAdded: string;
  properties?: PropertyReference[];
}
/**
 * An datam8 abstract internal data type.
 */

export interface AttributeType {
  name: string;
  displayName: string;
  description?: string;
  defaultType: string;
  defaultLength?: number;
  defaultPrecision?: number;
  defaultScale?: number;
  /**
   * Defines if an attribute should define a unit, e.g. `Physical` for weight or `Currency` for price.
   */
  hasUnit?: "NoUnit" | "Physical" | "Currency";
  canBeInRelation?: boolean;
  isDefaultProperty?: boolean;
}

// ---- zone.json ----

export interface Zone {
  /**
   * Logical name of the zone (e.g., Raw, Core, Curated)
   */
  name: string;
  /**
   * Target system name for the zone (e.g., Bronze, Silver, Gold)
   */
  targetName: string;
  /**
   * Human-readable display name
   */
  displayName: string;
  /**
   * Local folder name used in file system structure
   */
  localFolderName?: string;
  properties?: PropertyReference[];
}
/**
 * Used to reference from any entity to a `Property`.
 */

// ---- folder.json ----

export interface Folder {
  /**
   * Internal id of an entity.
   */
  id: number;
  name: string;
  displayName?: string;
  description?: string;
  /**
   * Path of this folder, if not set the current directory will be used.
   */
  path?: string;
  dataProduct?: string;
  dataModule?: string;
  properties?: PropertyReference[];
}

// ---- data-product.json ----

export interface DataProduct {
  name: string;
  displayName?: string;
  description?: string;
  properties?: PropertyReference[];
  /**
   * @minItems 1
   */
  dataModules: [DataModule, ...DataModule[]];
}
/**
 * Used to reference from any entity to a `Property`.
 */

export interface DataModule {
  name: string;
  displayName?: string;
  description?: string;
  properties?: PropertyReference[];
}

// ---- model.json ----

export type SourceAttributeMapping = ModelAttributeMapping & {
  sourceDataType?: DataType;
  properties?: PropertyReference[];
  [k: string]: unknown;
};
/**
 * Type of transformation, either `builtin` or `function`.
 */

export type TransformationKind = "builtin" | "function";
/**
 * Maps attributes to an internal or external target location.
 *
 * This interface was referenced by `ModelEntity`'s JSON-Schema
 * via the `definition` "ModelRelationship".
 */

export type ModelRelationship = {
  dataSource?: string;
  targetLocation: number | string;
  alias?: string;
  /**
   * @minItems 1
   */
  attributes: [ModelAttributeMapping, ...ModelAttributeMapping[]];
} & ModelRelationship1;

export type ModelRelationship1 =
  | {
      targetLocation: number;
      [k: string]: unknown;
    }
  | {
      targetLocation: string;
      [k: string]: unknown;
    };

/**
 * Describes a single entity within datam8. Most commonly a database table.
 */

export interface ModelEntity {
  /**
   * Internal id of an entity.
   */
  id: number;
  name: string;
  displayName?: string;
  description?: string;
  parameters?: ModelParameter[];
  /**
   * @minItems 1
   */
  attributes: [Attribute, ...Attribute[]];
  properties?: PropertyReference[];
  sources: (InternalModelSource | ExternalModelSource)[];
  /**
   * List of transformations that will be executed in order of stepNo.
   */
  transformations: ModelTransformation[];
  /**
   * List of entity relationships.
   */
  relationships: ModelRelationship[];
}
/**
 * Key-Value pair parameters for customization of and entity-level attributes.
 *
 * This interface was referenced by `ModelEntity`'s JSON-Schema
 * via the `definition` "ModelParameter".
 */

export interface ModelParameter {
  name: string;
  value:
    | string
    | {
        [k: string]: unknown;
      }
    | number
    | boolean;
}
/**
 * An attribute of a model entity.
 */

export interface InternalModelSource {
  sourceLocation: number;
  properties?: PropertyReference[];
  mapping?: SourceAttributeMapping[];
}
/**
 * Single attribute mapping.
 *
 * This interface was referenced by `ModelEntity`'s JSON-Schema
 * via the `definition` "ModelAttributeMapping".
 */

export interface ModelAttributeMapping {
  sourceName: string;
  targetName: string;
}
/**
 * Sources that point to external systems outside of datam8.
 *
 * This interface was referenced by `ModelEntity`'s JSON-Schema
 * via the `definition` "ExternalModelSource".
 */

export interface ExternalModelSource {
  dataSource: string;
  sourceAlias?: string;
  sourceLocation: string;
  properties?: PropertyReference[];
  mapping?: SourceAttributeMapping[];
}
/**
 * Describes a single transformation, either builtin or defined within the solution.
 *
 * This interface was referenced by `ModelEntity`'s JSON-Schema
 * via the `definition` "ModelTransformation".
 */

export interface ModelTransformation {
  stepNo: number;
  kind: TransformationKind;
  name: string;
  properties?: PropertyReference[];
  function?: TransformationFunction;
}
/**
 * A transformation function defined in the scope of the current solution.
 */

export interface TransformationFunction {
  source: string;
}
/**
 * Describes an abstract way to point to and find entities with datam8.
 *
 * This interface was referenced by `ModelEntity`'s JSON-Schema
 * via the `definition` "Locator".
 */

export interface Locator {
  entityType: string;
  /**
   * Hierarchical list of olders under the base-/modelpath. Order is relevant.
   */
  folders: string[];
  /**
   * Name property of the entity object.
   */
  entityName?: string;
}

// ---- plugin.json ----

export type Capability = "uiSchema" | "validationConnection" | "metadata" | "previewData";

/**
 * A DataM8 plugin that e.g. provides additional ways to connect to source systems
 */

export interface PluginManifest {
  id: string;
  /**
   * Human-readable display name
   */
  displayName?: string;
  version: string;
  /**
   * Python entrypoint that will be imported as a class of plugin
   */
  entryPoint: string;
  capabilities: Capability[];
}
/**
 * This interface was referenced by `PluginManifest`'s JSON-Schema
 * via the `definition` "UiSchema".
 */

export interface UiSchema {
  title: string;
  authModes: UiAuthMode[];
  [k: string]: unknown;
}

export interface UiAuthMode {
  id: string;
  label?: string;
  fields: UiField[];
  [k: string]: unknown;
}

export interface UiField {
  key: string;
  label?: string;
  type: string;
  required: boolean;
  default?: string | boolean | number | null;
  enum?: string[];
  [k: string]: unknown;
}

// ---- solution.json ----

export interface Solution {
  /**
   * Version of the schema for validation and migration support.
   */
  schemaVersion: string;
  /**
   * Root path for model entities, replacing zone-specific paths.
   */
  modelPath: string;
  /**
   * Path where base entity files like DataSources are stored.
   */
  basePath: string;
  /**
   * tbd
   */
  diagramPath?: string;
  /**
   * Path where connector plugins are stored.
   */
  pluginsPath: string;
  /**
   * Targets available to the generator when not explicitly specifying it.
   *
   * @minItems 1
   */
  generatorTargets: [GeneratorTarget, ...GeneratorTarget[]];
}
/**
 * Defines a target that can be selected when using the generator.
 *
 * This interface was referenced by `Solution`'s JSON-Schema
 * via the `definition` "GeneratorTarget".
 */

export interface GeneratorTarget {
  name: string;
  isDefault?: boolean;
  /**
   * A path relative to the folder where the the solution file lies.
   */
  sourcePath: string;
  /**
   * A path relative to the folder where the the solution file lies.
   */
  outputPath: string;
}

// ---- base.json ----

export type BaseEntities = {
  type?: EntityType;
  properties?: unknown;
  propertyValues?: unknown;
  zones?: unknown;
  dataTypes?: unknown;
  dataSourceTypes?: unknown;
  dataProducts?: unknown;
  dataModules?: unknown;
  attributeTypes?: unknown;
  dataSources?: unknown;
  folders?: unknown;
  modelEntities?: unknown;
  [k: string]: unknown;
} & (
  | ModelEntities
  | Folders
  | Properties
  | PropertyValues
  | Zones
  | DataTypes
  | DataSourceTypes
  | DataProducts
  | DataModules
  | AttributeTypes
  | DataSources
);
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "EntityType".
 */

export type EntityType =
  | "properties"
  | "propertyValues"
  | "zones"
  | "dataTypes"
  | "dataSourceTypes"
  | "dataProducts"
  | "dataModules"
  | "attributeTypes"
  | "dataSources"
  | "folders"
  | "modelEntities";
/**
 * A union type for all internal objects.
 *
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "BaseEntity".
 */

export type BaseEntity =
  | Property
  | PropertyValue
  | Zone
  | DataTypeDefinition
  | DataSourceType
  | DataProduct
  | DataModule
  | AttributeType
  | DataSource
  | Folder
  | ModelEntity;

export interface ModelEntities {
  type: "modelEntities";
  modelEntities: ModelEntity[];
}

export interface Folders {
  type: "folders";
  /**
   * @minItems 1
   */
  folders: [Folder, ...Folder[]];
}

export interface Properties {
  type: "properties";
  properties: Property[];
}

export interface PropertyValues {
  type: "propertyValues";
  propertyValues: PropertyValue[];
}

export interface Zones {
  type: "zones";
  zones: Zone[];
}

export interface DataTypes {
  type: "dataTypes";
  /**
   * @minItems 1
   */
  dataTypes: [DataTypeDefinition, ...DataTypeDefinition[]];
}

export interface DataSourceTypes {
  type: "dataSourceTypes";
  dataSourceTypes: DataSourceType[];
}

export interface DataProducts {
  type: "dataProducts";
  dataProducts: DataProduct[];
}

export interface DataModules {
  type: "dataModules";
  /**
   * @minItems 1
   */
  dataModules: [DataModule, ...DataModule[]];
}

export interface AttributeTypes {
  type: "attributeTypes";
  /**
   * @minItems 1
   */
  attributeTypes: [AttributeType, ...AttributeType[]];
}

export interface DataSources {
  type: "dataSources";
  dataSources: DataSource[];
}

// ---- diagram.json ----

export interface Diagram {
  diagramType?: string;
  coreEntities?: string[];
  diagramOptions?: DiagramOption[];
}

export interface DiagramOption {
  name: string;
  value: string;
}
