//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dm8Main {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light.Oragne")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Git\\bin")]
        public string GitPath {
            get {
                return ((string)(this["GitPath"]));
            }
            set {
                this["GitPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\MSBuild\\Current\\Bin\\ms" +
            "build.exe")]
        public string MsBuildPath {
            get {
                return ((string)(this["MsBuildPath"]));
            }
            set {
                this["MsBuildPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Python310")]
        public string PythonPath {
            get {
                return ((string)(this["PythonPath"]));
            }
            set {
                this["PythonPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-a refresh_generate -s \"${SolutionFilePath}\" -src \"${GeneratePath}\\__models\\stage" +
            ".jinja2\" -dest \"${StagingPath}\" -m \"${GeneratePath}\\databricks-lake\\__modules\" -" +
            "c \"${GeneratePath}\\databricks-lake\\__collections\"")]
        public string GeneratorParameterSTAGE_V2 {
            get {
                return ((string)(this["GeneratorParameterSTAGE_V2"]));
            }
            set {
                this["GeneratorParameterSTAGE_V2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-a refresh_generate -s \"${SolutionFilePath}\" -src \"${GeneratePath}\\databricks-lak" +
            "e\" -dest \"${OutputFolderPath}\" -m \"${GeneratePath}\\databricks-lake\\__modules\" -c" +
            " \"${GeneratePath}\\databricks-lake\\__collections\"")]
        public string GeneratorParameterOUTPUT_V2 {
            get {
                return ((string)(this["GeneratorParameterOUTPUT_V2"]));
            }
            set {
                this["GeneratorParameterOUTPUT_V2"] = value;
            }
        }
    }
}
