//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dm8Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dm8Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily - only computed once a day (paramter = hour:minute).
        /// </summary>
        public static string CuratedFunctionViewModel_daily {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merge - Merge result with content of target entity using the defined keys.
        /// </summary>
        public static string CuratedFunctionViewModel_merge {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly - only computed once a month (paramter = day of month + {hour:minute}).
        /// </summary>
        public static string CuratedFunctionViewModel_monthly {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no restriction - always computed whenever function is called.
        /// </summary>
        public static string CuratedFunctionViewModel_no_restriction {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_no_restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partition - Replace full partitions and merge with partitions not changed.
        /// </summary>
        public static string CuratedFunctionViewModel_partition {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace - Completely replace content of target entity with new result.
        /// </summary>
        public static string CuratedFunctionViewModel_replace {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self - Result is directly stored into the target entity.
        /// </summary>
        public static string CuratedFunctionViewModel_self {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekly - only computed once a week (paramter = day of week [Mo-Fr] + {hour:minute}).
        /// </summary>
        public static string CuratedFunctionViewModel_weekly {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yearly - only computed once a month (paramter = day of month + month + {hour:minute}).
        /// </summary>
        public static string CuratedFunctionViewModel_yearly {
            get {
                return ResourceManager.GetString("CuratedFunctionViewModel_yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Types.
        /// </summary>
        public static string Folder_Attribute_Types {
            get {
                return ResourceManager.GetString("Folder_Attribute_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Definitions.
        /// </summary>
        public static string Folder_Base_Definitions {
            get {
                return ResourceManager.GetString("Folder_Base_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Folder_Core {
            get {
                return ResourceManager.GetString("Folder_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated.
        /// </summary>
        public static string Folder_Curated {
            get {
                return ResourceManager.GetString("Folder_Curated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sources.
        /// </summary>
        public static string Folder_Data_Sources {
            get {
                return ResourceManager.GetString("Folder_Data_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Types.
        /// </summary>
        public static string Folder_Data_Types {
            get {
                return ResourceManager.GetString("Folder_Data_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Modules.
        /// </summary>
        public static string Folder_DataModules {
            get {
                return ResourceManager.GetString("Folder_DataModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Products.
        /// </summary>
        public static string Folder_DataProducts {
            get {
                return ResourceManager.GetString("Folder_DataProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string Folder_Diagram {
            get {
                return ResourceManager.GetString("Folder_Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Folder_Generate {
            get {
                return ResourceManager.GetString("Folder_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Folder_Output {
            get {
                return ResourceManager.GetString("Folder_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string Folder_Raw {
            get {
                return ResourceManager.GetString("Folder_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging.
        /// </summary>
        public static string Folder_Staging {
            get {
                return ResourceManager.GetString("Folder_Staging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Definitions.
        /// </summary>
        public static string Layer_Base {
            get {
                return ResourceManager.GetString("Layer_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Layer_Core {
            get {
                return ResourceManager.GetString("Layer_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated.
        /// </summary>
        public static string Layer_Curated {
            get {
                return ResourceManager.GetString("Layer_Curated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string Layer_Raw {
            get {
                return ResourceManager.GetString("Layer_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Layer_Stage {
            get {
                return ResourceManager.GetString("Layer_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize json {0}.
        /// </summary>
        public static string ModelReaderList_ReadFromStringAsync_Cannot_deserialize_json__0_ {
            get {
                return ResourceManager.GetString("ModelReaderList_ReadFromStringAsync_Cannot_deserialize_json__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read {0}.
        /// </summary>
        public static string ModelReaderList_ReadFromStringAsync_Cannot_read__0_ {
            get {
                return ResourceManager.GetString("ModelReaderList_ReadFromStringAsync_Cannot_read__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeTypes.json.
        /// </summary>
        public static string Solution_AttributeTypesFilePath_AttributeTypes_json {
            get {
                return ResourceManager.GetString("Solution_AttributeTypesFilePath_AttributeTypes_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Solution_BaseFilePath {
            get {
                return ResourceManager.GetString("Solution_BaseFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Solution_CoreFolderPath {
            get {
                return ResourceManager.GetString("Solution_CoreFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curated.
        /// </summary>
        public static string Solution_CuratedFolderPath {
            get {
                return ResourceManager.GetString("Solution_CuratedFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModules.json.
        /// </summary>
        public static string Solution_DataModulesFilePath_DataModules_json {
            get {
                return ResourceManager.GetString("Solution_DataModulesFilePath_DataModules_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataProducts.json.
        /// </summary>
        public static string Solution_DataProductsFilePath_DataProducts_json {
            get {
                return ResourceManager.GetString("Solution_DataProductsFilePath_DataProducts_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSources.json.
        /// </summary>
        public static string Solution_DataSourcesFilePath_DataSources_json {
            get {
                return ResourceManager.GetString("Solution_DataSourcesFilePath_DataSources_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTypes.json.
        /// </summary>
        public static string Solution_DataTypesFilePath_DataTypes_json {
            get {
                return ResourceManager.GetString("Solution_DataTypesFilePath_DataTypes_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string Solution_DiagramFolderPath {
            get {
                return ResourceManager.GetString("Solution_DiagramFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Solution_GenerateFolderPath {
            get {
                return ResourceManager.GetString("Solution_GenerateFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Solution_OutputFolderPath {
            get {
                return ResourceManager.GetString("Solution_OutputFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string Solution_RawFolderPath {
            get {
                return ResourceManager.GetString("Solution_RawFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging.
        /// </summary>
        public static string Solution_StagingFolderPath {
            get {
                return ResourceManager.GetString("Solution_StagingFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} not found in project (validate project/refresh cache).
        /// </summary>
        public static string SolutionHelper_GetOrCreateEntry_NotFound {
            get {
                return ResourceManager.GetString("SolutionHelper_GetOrCreateEntry_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Valid (no issue found).
        /// </summary>
        public static string Validate_NoError {
            get {
                return ResourceManager.GetString("Validate_NoError", resourceCulture);
            }
        }
    }
}
