name: "Lint, Build and Test (Reusable)"

on:
  workflow_call:
    inputs:
      upload_artifacts:
        type: boolean
        required: true

jobs:
  linting:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: true

      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          uv_version: "0.11.0"
          python_version_file: ".python-version"

      - name: Run ruff lint check
        run: uvx ruff check . --respect-gitignore --exclude datam8-model/

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run ty code analysis
        run: uvx ty check src

      # TODO: deactivate for now due to false positives with generics
      # - name: Run pyright code analysis
      #   run: uvx  src

  building:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: true

      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          uv_version: "0.8.17"
          python_version_file: ".python-version"

      - name: Build the application
        run: uv build

      - name: Upload Build Artifacts
        if: ${{ inputs.upload_artifacts }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: dist-artifacts
          path: dist

  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: true

      - name: Check out solution repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          repository: oraylis/datam8-sample-solution
          # TODO: remove after v2 is done
          ref: v2.0.0-beta.1
          path: datam8-sample-solution

      - name: Set up environment
        uses: ./.github/actions/setup-environment
        with:
          uv_version: "0.8.17"
          python_version_file: ".python-version"

      - name: Set solution environment variable
        run: |
          echo "DATAM8_SOLUTION_PATH=datam8-sample-solution/ORAYLISDatabricksSample.dm8s" >> $GITHUB_ENV

      - name: Install packages
        run: uv sync --all-extras

      - name: Run pytests
        run: uv run pytest --junitxml=TEST-generator-pytest.xml
        continue-on-error: true
        env:
          NO_COLOR: 1
          FORCE_COLOR: 0
          TERM: dumb

      - name: Publish Test Results
        uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2.6.0
        with:
          name: Pytest Results
          path: TEST-generator-pytest.xml
          reporter: java-junit

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: pytest-results
          path: TEST-generator-pytest.xml
