name: "Build, Sign, and Release on PR from Main"

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  build-sign-tag-and-release:
    runs-on: windows-latest
    env:
      dotNetVersion: "8.0.x"
      azureSignToolVersion: "6.0.0"
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out solution respoitory
        uses: actions/checkout@v4
        with:
          repository: oraylis/automation-sample-solution
          token: ${{ secrets.DATAM8_SAMPLE_SOLUTION_PAT }}
          path: automation-sample-solution

      - name: Integrate latest version of sample solution generator into frontend
        run: |
          Copy-Item `
          -Path automation-sample-solution/Generate/* `
          -Destination src/Dm8Main/Solution/CreateNewProject/Generate/ `
          -Recurse `
          -Force

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotNetVersion }}

      - name: Dotnet Restore
        run: dotnet restore src/Dm8Main.sln

      - name: Dotnet Build DataM8 Solution
        run: dotnet build src/Dm8Main.sln

      - name: Dotnet Build Validator CLI for Linux
        run: |
          dotnet build src/Dm8Validate/Dm8Validate.csproj `
          -c Debug_Linux `
          -r linux-x64 `
          --self-contained

      - name: Dotnet Install WIX
        run: dotnet tool install --global wix

      - name: WIX add dependencies
        run: wix.exe extension add -g WixToolset.UI.wixext/5.0.2

      - name: Dotnet Build Setup
        run: dotnet build src/Dm8Setup/Dm8Setup.csproj

      - name: Extract project version from App.config
        run: |
          $version = Select-String `
          -Path "src/App.config" `
          -Pattern 'Version=(\d+\.\d+\.\d+)' | Select-Object `
          -First 1 | ForEach-Object { $_.Matches[0].Groups[1].Value }
          echo "VERSION=v$version" >> $env:GITHUB_ENV

      - name: Get latest tag version
        run: |
          $latest_tag_version = git tag --list | Sort-Object `
          -Descending | Select-Object `
          -First 1
          echo "LATEST_TAG_VERSION=$latest_tag_version" >> $env:GITHUB_ENV

      - name: Generate commit log
        if: env.VERSION != env.LATEST_TAG_VERSION
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"

          # Fetch the latest commits
          if git rev-parse "$LATEST_TAG_VERSION" >/dev/null 2>&1; then
            LOG=$(git log "$LATEST_TAG_VERSION"..HEAD --pretty=format:"| [\`%h\`]($REPO_URL/commit/%H) | %s |" --reverse)
          else
            LOG=$(git log --pretty=format:"| [\`%h\`]($REPO_URL/commit/%H) | %s |" --reverse)
          fi

          printf "CHANGELOG<<EOF\n| Commit ID | Commit Message |\n|-----------|---------------|\n%s\nEOF\n" "$LOG" >> "$GITHUB_ENV"

      - name: Dotnet Install Azure SignTool
        if: env.VERSION != env.LATEST_TAG_VERSION
        run: |
          dotnet tool install `
          --global AzureSignTool `
          --version ${{ env.azureSignToolVersion }}

      - name: Sign installer and executables
        if: env.VERSION != env.LATEST_TAG_VERSION
        run: |
          AzureSignTool sign `
            -kvt ${{ secrets.AZURE_KEY_VAULT_TENANT }} `
            -kvu ${{ secrets.AZURE_KEY_VAULT_URL }} `
            -kvi ${{ secrets.AZURE_KEY_VAULT_ID }} `
            -kvs ${{ secrets.AZURE_KEY_VAULT_SECRET }} `
            -kvc ${{ secrets.AZURE_KEY_VAULT_NAME }} `
            -tr http://timestamp.digicert.com `
            -v `
            "src/Dm8Setup/bin/Debug/ORAYLIS DataM8.msi" `
            src/Dm8Main/bin/Debug/net8.0-windows7.0/Dm8Main.exe `
            src/Dm8Validate/bin/Debug/net8.0/Dm8Validate.exe

      - name: Zip DataM8
        if: env.VERSION != env.LATEST_TAG_VERSION
        run: |
          Compress-Archive `
          -Path src/Dm8Main/bin/Debug/net8.0-windows7.0/* `
          -DestinationPath src/DataM8.win-x64.zip

      - name: Zip DataM8 Validator for Windows
        if: env.VERSION != env.LATEST_TAG_VERSION
        run: |
          Compress-Archive `
          -Path src/Dm8Validate/bin/Debug/net8.0/* `
          -DestinationPath src/DataM8Validate.win-x64.zip

      - name: Zip DataM8 Validator for Linux
        if: env.VERSION != env.LATEST_TAG_VERSION
        run: |
          Compress-Archive `
          -Path src/Dm8Validate/bin/Debug_Linux/net8.0/linux-x64/* `
          -DestinationPath src/DataM8Validate.linux-x64.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: env.VERSION != env.LATEST_TAG_VERSION
        with:
          tag_name: ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          generate_release_notes: true
          files: |
            src/DataM8.win-x64.zip
            src/DataM8Validate.win-x64.zip
            src/DataM8Validate.linux-x64.zip
            src/Dm8Setup/bin/Debug/*.msi
