//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dm8Main.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dm8Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Attribute ähnelt.
        /// </summary>
        public static string CoreAttributeEdit_Title {
            get {
                return ResourceManager.GetString("CoreAttributeEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define Core Entity ähnelt.
        /// </summary>
        public static string CoreEntityAdd_TabItem_Header_CoreEntity {
            get {
                return ResourceManager.GetString("CoreEntityAdd.TabItem.Header.CoreEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Source Entities ähnelt.
        /// </summary>
        public static string CoreEntityAdd_TabItem_Header_SourceEntity {
            get {
                return ResourceManager.GetString("CoreEntityAdd.TabItem.Header.SourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assign ähnelt.
        /// </summary>
        public static string CoreModelEntry_Header_Assign {
            get {
                return ResourceManager.GetString("CoreModelEntry.Header.Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string CoreModelEntry_Header_Edit {
            get {
                return ResourceManager.GetString("CoreModelEntry.Header.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Entity {0} is reference by:
        ///	
        ///	{1}.
        ///
        ///Check if renamed column is influencing the referenced objects (incl. auto save)? ähnelt.
        /// </summary>
        public static string CoreModelEntryViewModel_CheckReferences {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_CheckReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You renamed the entity. Should the file name and all referenced be changed as well? ähnelt.
        /// </summary>
        public static string CoreModelEntryViewModel_EntityOnPropertyChanged_Message {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_EntityOnPropertyChanged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Core Entity Renamed ähnelt.
        /// </summary>
        public static string CoreModelEntryViewModel_EntityOnPropertyChanged_Title {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_EntityOnPropertyChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Referenced Entities ähnelt.
        /// </summary>
        public static string CoreModelEntryViewModel_Update_Referenced_Entities {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_Update_Referenced_Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removed mapping to unknown source attribute {0} from {1} ähnelt.
        /// </summary>
        public static string CoreModelEntryViewModel_Wrong_Mapping {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_Wrong_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define Curated Entity ähnelt.
        /// </summary>
        public static string CuratedEntityAdd_TabItem_Header_CuratedEntity {
            get {
                return ResourceManager.GetString("CuratedEntityAdd.TabItem.Header.CuratedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Source Entities ähnelt.
        /// </summary>
        public static string CuratedEntityAdd_TabItem_Header_SourceEntity {
            get {
                return ResourceManager.GetString("CuratedEntityAdd.TabItem.Header.SourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string DataGridTemplateColumn_Header {
            get {
                return ResourceManager.GetString("DataGridTemplateColumn.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Source Edit ähnelt.
        /// </summary>
        public static string DataSourceEdit_Title {
            get {
                return ResourceManager.GetString("DataSourceEdit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raw Model Entry ähnelt.
        /// </summary>
        public static string DlgRawModelEntryAdd_Title {
            get {
                return ResourceManager.GetString("DlgRawModelEntryAdd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a message ähnelt.
        /// </summary>
        public static string GitView_EnterMessage {
            get {
                return ResourceManager.GetString("GitView_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;LayoutRoot&gt;&lt;RootPanel Orientation=&quot;Horizontal&quot;&gt;&lt;LayoutPanel Orientation=&quot;Vertical&quot;&gt;&lt;LayoutPanel Orientation=&quot;Horizontal&quot; DockHeight=&quot;1.2892441860465111*&quot;&gt;&lt;LayoutPanel Orientation=&quot;Vertical&quot;&gt;&lt;LayoutPanel Orientation=&quot;Horizontal&quot;&gt;&lt;LayoutPanel Orientation=&quot;Horizontal&quot;&gt;&lt;LayoutDocumentPaneGroup Orientation=&quot;Horizontal&quot;&gt;&lt;LayoutDocumentPane Id=&quot;7ee2ef65-4ca0-4c45-a474-c1e2d07cf1db&quot; /&gt;&lt;/LayoutDocumentPaneGroup&gt;&lt;/LayoutPanel&gt;&lt;/LayoutPanel&gt;&lt;LayoutAnchorablePaneGroup Orientation [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string Layout_Default {
            get {
                return ResourceManager.GetString("Layout_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Curated Entity ähnelt.
        /// </summary>
        public static string Main_AddCurated_ToolTip {
            get {
                return ResourceManager.GetString("Main.AddCurated.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Source Entity ähnelt.
        /// </summary>
        public static string Main_AddRaw_ToolTip {
            get {
                return ResourceManager.GetString("Main.AddRaw.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate ähnelt.
        /// </summary>
        public static string Main_Generate {
            get {
                return ResourceManager.GetString("Main_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Git ähnelt.
        /// </summary>
        public static string Main_Git {
            get {
                return ResourceManager.GetString("Main_Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Git Window ähnelt.
        /// </summary>
        public static string Main_Git_ToolTip {
            get {
                return ResourceManager.GetString("Main.Git.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string Main_Help {
            get {
                return ResourceManager.GetString("Main_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string Main_Help_ToolTip {
            get {
                return ResourceManager.GetString("Main.Help.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string Main_Home {
            get {
                return ResourceManager.GetString("Main_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string Main_New {
            get {
                return ResourceManager.GetString("Main_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new project ähnelt.
        /// </summary>
        public static string Main_New_ToolTip {
            get {
                return ResourceManager.GetString("Main.New.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string Main_Open {
            get {
                return ResourceManager.GetString("Main_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open existing project ähnelt.
        /// </summary>
        public static string Main_Open_ToolTip {
            get {
                return ResourceManager.GetString("Main.Open.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        public static string Main_Output {
            get {
                return ResourceManager.GetString("Main_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Output Window ähnelt.
        /// </summary>
        public static string Main_Output_ToolTip {
            get {
                return ResourceManager.GetString("Main.Output.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string Main_Project {
            get {
                return ResourceManager.GetString("Main_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Project Explorer ähnelt.
        /// </summary>
        public static string Main_Project_ToolTip {
            get {
                return ResourceManager.GetString("Main.Project.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh Complete Source ähnelt.
        /// </summary>
        public static string Main_RefreshSource_ToolTip {
            get {
                return ResourceManager.GetString("Main.RefreshSource.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Main_Save {
            get {
                return ResourceManager.GetString("Main_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save (Ctrl+S) ähnelt.
        /// </summary>
        public static string Main_Save_ToolTip {
            get {
                return ResourceManager.GetString("Main.Save.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save All ähnelt.
        /// </summary>
        public static string Main_SaveAll {
            get {
                return ResourceManager.GetString("Main_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save all files (Ctrl+Shift+S) ähnelt.
        /// </summary>
        public static string Main_SaveAll_ToolTip {
            get {
                return ResourceManager.GetString("Main.SaveAll.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show main settings ähnelt.
        /// </summary>
        public static string Main_Settings_ToolTip {
            get {
                return ResourceManager.GetString("Main.Settings.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution ähnelt.
        /// </summary>
        public static string Main_Solution {
            get {
                return ResourceManager.GetString("Main_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validate ähnelt.
        /// </summary>
        public static string Main_Validate {
            get {
                return ResourceManager.GetString("Main_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validate Project ähnelt.
        /// </summary>
        public static string Main_Validate_ToolTip {
            get {
                return ResourceManager.GetString("Main.Validate.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string Main_View {
            get {
                return ResourceManager.GetString("Main_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Core ähnelt.
        /// </summary>
        public static string MainWindow_AddCore_Header {
            get {
                return ResourceManager.GetString("MainWindow.AddCore.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New Core Entity ähnelt.
        /// </summary>
        public static string MainWindow_AddCore_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow.AddCore.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate Output ähnelt.
        /// </summary>
        public static string MainWindow_AddOutput_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow.AddOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Stage ähnelt.
        /// </summary>
        public static string MainWindow_AddStage_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow.AddStage.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Curated ähnelt.
        /// </summary>
        public static string Menu_AddCurated {
            get {
                return ResourceManager.GetString("Menu_AddCurated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Raw ähnelt.
        /// </summary>
        public static string Menu_AddRaw {
            get {
                return ResourceManager.GetString("Menu_AddRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete File ähnelt.
        /// </summary>
        public static string Menu_DeleteFile {
            get {
                return ResourceManager.GetString("Menu_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Folder ähnelt.
        /// </summary>
        public static string Menu_DeleteFolder {
            get {
                return ResourceManager.GetString("Menu_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate Output ähnelt.
        /// </summary>
        public static string Menu_GenerateOutput {
            get {
                return ResourceManager.GetString("Menu_GenerateOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate Stage ähnelt.
        /// </summary>
        public static string Menu_GenerateStage {
            get {
                return ResourceManager.GetString("Menu_GenerateStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Folder ähnelt.
        /// </summary>
        public static string Menu_NewFolder {
            get {
                return ResourceManager.GetString("Menu_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New .Jinja2 Template ähnelt.
        /// </summary>
        public static string Menu_NewJinja2Generate {
            get {
                return ResourceManager.GetString("Menu_NewJinja2Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Python Code Generator ähnelt.
        /// </summary>
        public static string Menu_NewPythonGenerate {
            get {
                return ResourceManager.GetString("Menu_NewPythonGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Raw Entity ähnelt.
        /// </summary>
        public static string Menu_NewSourceEntity {
            get {
                return ResourceManager.GetString("Menu_NewSourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New T4 Code Generator ähnelt.
        /// </summary>
        public static string Menu_NewT4Generate {
            get {
                return ResourceManager.GetString("Menu_NewT4Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open File ähnelt.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh Raw Entities ähnelt.
        /// </summary>
        public static string Menu_RefreshRaw {
            get {
                return ResourceManager.GetString("Menu_RefreshRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename File ähnelt.
        /// </summary>
        public static string Menu_RenameFile {
            get {
                return ResourceManager.GetString("Menu_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename Folder ähnelt.
        /// </summary>
        public static string Menu_RenameFolder {
            get {
                return ResourceManager.GetString("Menu_RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} is modified.
        ///Do you want to save changes before closing the file? ähnelt.
        /// </summary>
        public static string Message_CloseAsync_Save {
            get {
                return ResourceManager.GetString("Message_CloseAsync_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete file {0} ähnelt.
        /// </summary>
        public static string Message_DeleteFile {
            get {
                return ResourceManager.GetString("Message_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete {0} files? ähnelt.
        /// </summary>
        public static string Message_DeleteFiles {
            get {
                return ResourceManager.GetString("Message_DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete folder {0}? ähnelt.
        /// </summary>
        public static string Message_DeleteFolder {
            get {
                return ResourceManager.GetString("Message_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete {0} folders? ähnelt.
        /// </summary>
        public static string Message_DeleteFolders {
            get {
                return ResourceManager.GetString("Message_DeleteFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Compute ähnelt.
        /// </summary>
        public static string Model_CuratedDefaultFunctionName {
            get {
                return ResourceManager.GetString("Model_CuratedDefaultFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate ähnelt.
        /// </summary>
        public static string OutputViewModel_Generate {
            get {
                return ResourceManager.GetString("OutputViewModel_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Git ähnelt.
        /// </summary>
        public static string OutputViewModel_Git {
            get {
                return ResourceManager.GetString("OutputViewModel_Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mermaid ähnelt.
        /// </summary>
        public static string OutputViewModel_Mermaid {
            get {
                return ResourceManager.GetString("OutputViewModel_Mermaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model Validation ähnelt.
        /// </summary>
        public static string OutputViewModel_Model_Validation {
            get {
                return ResourceManager.GetString("OutputViewModel_Model_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;ItemGroup&gt;
        ///    &lt;None Update=&quot;@File.tt&quot;&gt;
        ///      &lt;Generator&gt;TextTemplatingFilePreprocessor&lt;/Generator&gt;
        ///      &lt;LastGenOutput&gt;@File.cs&lt;/LastGenOutput&gt;
        ///    &lt;/None&gt;
        ///    &lt;Compile Update=&quot;@File.cs&quot;&gt;
        ///      &lt;DesignTime&gt;True&lt;/DesignTime&gt;
        ///      &lt;AutoGen&gt;True&lt;/AutoGen&gt;
        ///      &lt;DependentUpon&gt;@File.tt&lt;/DependentUpon&gt;
        ///    &lt;/Compile&gt;
        ///  &lt;/ItemGroup&gt; ähnelt.
        /// </summary>
        public static string Project_Template {
            get {
                return ResourceManager.GetString("Project_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display Name ähnelt.
        /// </summary>
        public static string RawEntity_DisplayName {
            get {
                return ResourceManager.GetString("RawEntity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity Name ähnelt.
        /// </summary>
        public static string RawEntity_Name {
            get {
                return ResourceManager.GetString("RawEntity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source Name ähnelt.
        /// </summary>
        public static string RawEntity_SourceName {
            get {
                return ResourceManager.GetString("RawEntity_SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You renamed the entity. Should the file name be changed as well (incl. automatic save)? ähnelt.
        /// </summary>
        public static string RawModelEntryViewModel_EntityOnPropertyChanged_Message {
            get {
                return ResourceManager.GetString("RawModelEntryViewModel_EntityOnPropertyChanged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raw Entity Renamed ähnelt.
        /// </summary>
        public static string RawModelEntryViewModel_EntityOnPropertyChanged_Title {
            get {
                return ResourceManager.GetString("RawModelEntryViewModel_EntityOnPropertyChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Attributes={0}/Deleted Attributes={1}/New Attributes={2} ähnelt.
        /// </summary>
        public static string RawModelEntryViewModel_RefreshSourceResult {
            get {
                return ResourceManager.GetString("RawModelEntryViewModel_RefreshSourceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Change ähnelt.
        /// </summary>
        public static string RawModelEntryViewModel_RefreshSourceResult_No_Change {
            get {
                return ResourceManager.GetString("RawModelEntryViewModel_RefreshSourceResult_No_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attribute Types ähnelt.
        /// </summary>
        public static string Title_AttributeTypes {
            get {
                return ResourceManager.GetString("Title_AttributeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new Datam8 solution ähnelt.
        /// </summary>
        public static string Title_CreateSolution {
            get {
                return ResourceManager.GetString("Title_CreateSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Modules ähnelt.
        /// </summary>
        public static string Title_DataModules {
            get {
                return ResourceManager.GetString("Title_DataModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Products ähnelt.
        /// </summary>
        public static string Title_DataProducts {
            get {
                return ResourceManager.GetString("Title_DataProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Sources ähnelt.
        /// </summary>
        public static string Title_DataSource {
            get {
                return ResourceManager.GetString("Title_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Types ähnelt.
        /// </summary>
        public static string Title_DataTypes {
            get {
                return ResourceManager.GetString("Title_DataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Exception occured ähnelt.
        /// </summary>
        public static string Title_Exception {
            get {
                return ResourceManager.GetString("Title_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Git ähnelt.
        /// </summary>
        public static string Title_Git {
            get {
                return ResourceManager.GetString("Title_Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ORAYLIS DataM8 ähnelt.
        /// </summary>
        public static string Title_Main {
            get {
                return ResourceManager.GetString("Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Datam8 Solution ähnelt.
        /// </summary>
        public static string Title_OpenSolution {
            get {
                return ResourceManager.GetString("Title_OpenSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        public static string Title_Output {
            get {
                return ResourceManager.GetString("Title_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string Title_Project {
            get {
                return ResourceManager.GetString("Title_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raw Entity ähnelt.
        /// </summary>
        public static string Title_RawEntity {
            get {
                return ResourceManager.GetString("Title_RawEntity", resourceCulture);
            }
        }
    }
}
