//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dm8Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dm8Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Attribute.
        /// </summary>
        public static string CoreAttributeEdit_Title {
            get {
                return ResourceManager.GetString("CoreAttributeEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Core Entity.
        /// </summary>
        public static string CoreEntityAdd_TabItem_Header_CoreEntity {
            get {
                return ResourceManager.GetString("CoreEntityAdd.TabItem.Header.CoreEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source Entities.
        /// </summary>
        public static string CoreEntityAdd_TabItem_Header_SourceEntity {
            get {
                return ResourceManager.GetString("CoreEntityAdd.TabItem.Header.SourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string CoreModelEntry_Header_Assign {
            get {
                return ResourceManager.GetString("CoreModelEntry.Header.Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CoreModelEntry_Header_Edit {
            get {
                return ResourceManager.GetString("CoreModelEntry.Header.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Entity {0} is reference by:
        ///	
        ///	{1}.
        ///
        ///Check if renamed column is influencing the referenced objects (incl. auto save)?.
        /// </summary>
        public static string CoreModelEntryViewModel_CheckReferences {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_CheckReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You renamed the entity. Should the file name and all referenced be changed as well?.
        /// </summary>
        public static string CoreModelEntryViewModel_EntityOnPropertyChanged_Message {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_EntityOnPropertyChanged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Entity Renamed.
        /// </summary>
        public static string CoreModelEntryViewModel_EntityOnPropertyChanged_Title {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_EntityOnPropertyChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Referenced Entities.
        /// </summary>
        public static string CoreModelEntryViewModel_Update_Referenced_Entities {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_Update_Referenced_Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed mapping to unknown source attribute {0} from {1}.
        /// </summary>
        public static string CoreModelEntryViewModel_Wrong_Mapping {
            get {
                return ResourceManager.GetString("CoreModelEntryViewModel_Wrong_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Curated Entity.
        /// </summary>
        public static string CuratedEntityAdd_TabItem_Header_CuratedEntity {
            get {
                return ResourceManager.GetString("CuratedEntityAdd.TabItem.Header.CuratedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source Entities.
        /// </summary>
        public static string CuratedEntityAdd_TabItem_Header_SourceEntity {
            get {
                return ResourceManager.GetString("CuratedEntityAdd.TabItem.Header.SourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DataGridTemplateColumn_Header {
            get {
                return ResourceManager.GetString("DataGridTemplateColumn.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source Edit.
        /// </summary>
        public static string DataSourceEdit_Title {
            get {
                return ResourceManager.GetString("DataSourceEdit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Model Entry.
        /// </summary>
        public static string DlgRawModelEntryAdd_Title {
            get {
                return ResourceManager.GetString("DlgRawModelEntryAdd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a message.
        /// </summary>
        public static string GitView_EnterMessage {
            get {
                return ResourceManager.GetString("GitView_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;LayoutRoot&gt;&lt;RootPanel Orientation=&quot;Horizontal&quot;&gt;&lt;LayoutPanel Orientation=&quot;Vertical&quot;&gt;&lt;LayoutPanel Orientation=&quot;Horizontal&quot; DockHeight=&quot;1.2892441860465111*&quot;&gt;&lt;LayoutPanel Orientation=&quot;Vertical&quot;&gt;&lt;LayoutPanel Orientation=&quot;Horizontal&quot;&gt;&lt;LayoutPanel Orientation=&quot;Horizontal&quot;&gt;&lt;LayoutDocumentPaneGroup Orientation=&quot;Horizontal&quot;&gt;&lt;LayoutDocumentPane Id=&quot;7ee2ef65-4ca0-4c45-a474-c1e2d07cf1db&quot; /&gt;&lt;/LayoutDocumentPaneGroup&gt;&lt;/LayoutPanel&gt;&lt;/LayoutPanel&gt;&lt;LayoutAnchorablePaneGroup Orientation [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Layout_Default {
            get {
                return ResourceManager.GetString("Layout_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Curated Entity.
        /// </summary>
        public static string Main_AddCurated_ToolTip {
            get {
                return ResourceManager.GetString("Main.AddCurated.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Source Entity.
        /// </summary>
        public static string Main_AddRaw_ToolTip {
            get {
                return ResourceManager.GetString("Main.AddRaw.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Main_Generate {
            get {
                return ResourceManager.GetString("Main_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.
        /// </summary>
        public static string Main_Git {
            get {
                return ResourceManager.GetString("Main_Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Git Window.
        /// </summary>
        public static string Main_Git_ToolTip {
            get {
                return ResourceManager.GetString("Main.Git.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Main_Help {
            get {
                return ResourceManager.GetString("Main_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Main_Help_ToolTip {
            get {
                return ResourceManager.GetString("Main.Help.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Main_Home {
            get {
                return ResourceManager.GetString("Main_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Main_New {
            get {
                return ResourceManager.GetString("Main_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string Main_New_ToolTip {
            get {
                return ResourceManager.GetString("Main.New.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Main_Open {
            get {
                return ResourceManager.GetString("Main_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing project.
        /// </summary>
        public static string Main_Open_ToolTip {
            get {
                return ResourceManager.GetString("Main.Open.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Main_Output {
            get {
                return ResourceManager.GetString("Main_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Output Window.
        /// </summary>
        public static string Main_Output_ToolTip {
            get {
                return ResourceManager.GetString("Main.Output.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Main_Project {
            get {
                return ResourceManager.GetString("Main_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Project Explorer.
        /// </summary>
        public static string Main_Project_ToolTip {
            get {
                return ResourceManager.GetString("Main.Project.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Complete Source.
        /// </summary>
        public static string Main_RefreshSource_ToolTip {
            get {
                return ResourceManager.GetString("Main.RefreshSource.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Main_Save {
            get {
                return ResourceManager.GetString("Main_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl+S).
        /// </summary>
        public static string Main_Save_ToolTip {
            get {
                return ResourceManager.GetString("Main.Save.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string Main_SaveAll {
            get {
                return ResourceManager.GetString("Main_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all files (Ctrl+Shift+S).
        /// </summary>
        public static string Main_SaveAll_ToolTip {
            get {
                return ResourceManager.GetString("Main.SaveAll.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show main settings.
        /// </summary>
        public static string Main_Settings_ToolTip {
            get {
                return ResourceManager.GetString("Main.Settings.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string Main_Solution {
            get {
                return ResourceManager.GetString("Main_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Main_Validate {
            get {
                return ResourceManager.GetString("Main_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Project.
        /// </summary>
        public static string Main_Validate_ToolTip {
            get {
                return ResourceManager.GetString("Main.Validate.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Main_View {
            get {
                return ResourceManager.GetString("Main_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Core.
        /// </summary>
        public static string MainWindow_AddCore_Header {
            get {
                return ResourceManager.GetString("MainWindow.AddCore.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Core Entity.
        /// </summary>
        public static string MainWindow_AddCore_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow.AddCore.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Output.
        /// </summary>
        public static string MainWindow_AddOutput_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow.AddOutput.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stage.
        /// </summary>
        public static string MainWindow_AddStage_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow.AddStage.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Curated.
        /// </summary>
        public static string Menu_AddCurated {
            get {
                return ResourceManager.GetString("Menu_AddCurated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Raw.
        /// </summary>
        public static string Menu_AddRaw {
            get {
                return ResourceManager.GetString("Menu_AddRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string Menu_DeleteFile {
            get {
                return ResourceManager.GetString("Menu_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder.
        /// </summary>
        public static string Menu_DeleteFolder {
            get {
                return ResourceManager.GetString("Menu_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Output.
        /// </summary>
        public static string Menu_GenerateOutput {
            get {
                return ResourceManager.GetString("Menu_GenerateOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Stage.
        /// </summary>
        public static string Menu_GenerateStage {
            get {
                return ResourceManager.GetString("Menu_GenerateStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string Menu_NewFolder {
            get {
                return ResourceManager.GetString("Menu_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New .Jinja2 Template.
        /// </summary>
        public static string Menu_NewJinja2Generate {
            get {
                return ResourceManager.GetString("Menu_NewJinja2Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Python Code Generator.
        /// </summary>
        public static string Menu_NewPythonGenerate {
            get {
                return ResourceManager.GetString("Menu_NewPythonGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Raw Entity.
        /// </summary>
        public static string Menu_NewSourceEntity {
            get {
                return ResourceManager.GetString("Menu_NewSourceEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New T4 Code Generator.
        /// </summary>
        public static string Menu_NewT4Generate {
            get {
                return ResourceManager.GetString("Menu_NewT4Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Raw Entities.
        /// </summary>
        public static string Menu_RefreshRaw {
            get {
                return ResourceManager.GetString("Menu_RefreshRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        public static string Menu_RenameFile {
            get {
                return ResourceManager.GetString("Menu_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        public static string Menu_RenameFolder {
            get {
                return ResourceManager.GetString("Menu_RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is modified.
        ///Do you want to save changes before closing the file?.
        /// </summary>
        public static string Message_CloseAsync_Save {
            get {
                return ResourceManager.GetString("Message_CloseAsync_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete file {0}.
        /// </summary>
        public static string Message_DeleteFile {
            get {
                return ResourceManager.GetString("Message_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete {0} files?.
        /// </summary>
        public static string Message_DeleteFiles {
            get {
                return ResourceManager.GetString("Message_DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete folder {0}?.
        /// </summary>
        public static string Message_DeleteFolder {
            get {
                return ResourceManager.GetString("Message_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete {0} folders?.
        /// </summary>
        public static string Message_DeleteFolders {
            get {
                return ResourceManager.GetString("Message_DeleteFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Compute.
        /// </summary>
        public static string Model_CuratedDefaultFunctionName {
            get {
                return ResourceManager.GetString("Model_CuratedDefaultFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string OutputViewModel_Generate {
            get {
                return ResourceManager.GetString("OutputViewModel_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.
        /// </summary>
        public static string OutputViewModel_Git {
            get {
                return ResourceManager.GetString("OutputViewModel_Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mermaid.
        /// </summary>
        public static string OutputViewModel_Mermaid {
            get {
                return ResourceManager.GetString("OutputViewModel_Mermaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Validation.
        /// </summary>
        public static string OutputViewModel_Model_Validation {
            get {
                return ResourceManager.GetString("OutputViewModel_Model_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ItemGroup&gt;
        ///    &lt;None Update=&quot;@File.tt&quot;&gt;
        ///      &lt;Generator&gt;TextTemplatingFilePreprocessor&lt;/Generator&gt;
        ///      &lt;LastGenOutput&gt;@File.cs&lt;/LastGenOutput&gt;
        ///    &lt;/None&gt;
        ///    &lt;Compile Update=&quot;@File.cs&quot;&gt;
        ///      &lt;DesignTime&gt;True&lt;/DesignTime&gt;
        ///      &lt;AutoGen&gt;True&lt;/AutoGen&gt;
        ///      &lt;DependentUpon&gt;@File.tt&lt;/DependentUpon&gt;
        ///    &lt;/Compile&gt;
        ///  &lt;/ItemGroup&gt;.
        /// </summary>
        public static string Project_Template {
            get {
                return ResourceManager.GetString("Project_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string RawEntity_DisplayName {
            get {
                return ResourceManager.GetString("RawEntity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Name.
        /// </summary>
        public static string RawEntity_Name {
            get {
                return ResourceManager.GetString("RawEntity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name.
        /// </summary>
        public static string RawEntity_SourceName {
            get {
                return ResourceManager.GetString("RawEntity_SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You renamed the entity. Should the file name be changed as well (incl. automatic save)?.
        /// </summary>
        public static string RawModelEntryViewModel_EntityOnPropertyChanged_Message {
            get {
                return ResourceManager.GetString("RawModelEntryViewModel_EntityOnPropertyChanged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Entity Renamed.
        /// </summary>
        public static string RawModelEntryViewModel_EntityOnPropertyChanged_Title {
            get {
                return ResourceManager.GetString("RawModelEntryViewModel_EntityOnPropertyChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Attributes={0}/Deleted Attributes={1}.
        /// </summary>
        public static string RawModelEntryViewModel_RefreshSourceResult {
            get {
                return ResourceManager.GetString("RawModelEntryViewModel_RefreshSourceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change.
        /// </summary>
        public static string RawModelEntryViewModel_RefreshSourceResult_No_Change {
            get {
                return ResourceManager.GetString("RawModelEntryViewModel_RefreshSourceResult_No_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Types.
        /// </summary>
        public static string Title_AttributeTypes {
            get {
                return ResourceManager.GetString("Title_AttributeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Datam8 solution.
        /// </summary>
        public static string Title_CreateSolution {
            get {
                return ResourceManager.GetString("Title_CreateSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Modules.
        /// </summary>
        public static string Title_DataModules {
            get {
                return ResourceManager.GetString("Title_DataModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Products.
        /// </summary>
        public static string Title_DataProducts {
            get {
                return ResourceManager.GetString("Title_DataProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sources.
        /// </summary>
        public static string Title_DataSource {
            get {
                return ResourceManager.GetString("Title_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Types.
        /// </summary>
        public static string Title_DataTypes {
            get {
                return ResourceManager.GetString("Title_DataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception occured.
        /// </summary>
        public static string Title_Exception {
            get {
                return ResourceManager.GetString("Title_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.
        /// </summary>
        public static string Title_Git {
            get {
                return ResourceManager.GetString("Title_Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORAYLIS DataM8.
        /// </summary>
        public static string Title_Main {
            get {
                return ResourceManager.GetString("Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Datam8 Solution.
        /// </summary>
        public static string Title_OpenSolution {
            get {
                return ResourceManager.GetString("Title_OpenSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Title_Output {
            get {
                return ResourceManager.GetString("Title_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Title_Project {
            get {
                return ResourceManager.GetString("Title_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Entity.
        /// </summary>
        public static string Title_RawEntity {
            get {
                return ResourceManager.GetString("Title_RawEntity", resourceCulture);
            }
        }
    }
}
