//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dm8Main.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>100</string>
  <string>100</string>
  <string>900</string>
  <string>700</string>
  <string>Normal</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MainWindowSetting {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MainWindowSetting"]));
            }
            set {
                this["MainWindowSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>300</string>
  <string>100</string>
  <string>600</string>
  <string>700</string>
  <string>Normal</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DlgAddSourceSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DlgAddSourceSettings"]));
            }
            set {
                this["DlgAddSourceSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>300</string>
  <string>100</string>
  <string>600</string>
  <string>700</string>
  <string>Normal</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DlgCoreEntityAddSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DlgCoreEntityAddSettings"]));
            }
            set {
                this["DlgCoreEntityAddSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>300</string>
  <string>100</string>
  <string>600</string>
  <string>700</string>
  <string>Normal</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DlgCoreAttributeEditSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DlgCoreAttributeEditSettings"]));
            }
            set {
                this["DlgCoreAttributeEditSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>300</string>
  <string>100</string>
  <string>600</string>
  <string>700</string>
  <string>Normal</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DlgCoreEntityEditRelationshipSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DlgCoreEntityEditRelationshipSettings"]));
            }
            set {
                this["DlgCoreEntityEditRelationshipSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>300</string>
  <string>100</string>
  <string>600</string>
  <string>700</string>
  <string>Normal</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DlgCuratedEntityAddSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DlgCuratedEntityAddSettings"]));
            }
            set {
                this["DlgCuratedEntityAddSettings"] = value;
            }
        }
    }
}
